import sys
from numpy import expand_dims
from tensorflow.keras.preprocessing.image import img_to_array, load_img, save_img
from tensorflow_addons.layers import InstanceNormalization
from tensorflow.keras.models import load_model
import tensorflow as tf
import numpy as np
tf.get_logger().setLevel('ERROR')

birds_lst = [
"AFRICAN CROWNED CRANE","AFRICAN FIREFINCH","ALBATROSS","ALEXANDRINE PARAKEET","AMERICAN AVOCET","AMERICAN BITTERN","AMERICAN COOT","AMERICAN GOLDFINCH","AMERICAN KESTREL","AMERICAN PIPIT","AMERICAN REDSTART","ANHINGA","ANNAS HUMMINGBIRD","ANTBIRD","ARARIPE MANAKIN","ASIAN CRESTED IBIS","BALD EAGLE","BALI STARLING","BALTIMORE ORIOLE","BANANAQUIT","BANDED BROADBILL","BAR-TAILED GODWIT","BARN OWL","BARN SWALLOW","BARRED PUFFBIRD","BAY-BREASTED WARBLER","BEARDED BARBET","BELTED KINGFISHER","BIRD OF PARADISE","BLACK FRANCOLIN","BLACK SKIMMER","BLACK SWAN","BLACK THROATED WARBLER","BLACK VULTURE","BLACK-CAPPED CHICKADEE","BLACK-NECKED GREBE","BLACK-THROATED SPARROW","BLACKBURNIAM WARBLER","BLUE GROUSE","BLUE HERON","BOBOLINK","BROWN NOODY","BROWN THRASHER","CACTUS WREN","CALIFORNIA CONDOR","CALIFORNIA GULL","CALIFORNIA QUAIL","CANARY","CAPE MAY WARBLER","CAPUCHINBIRD","CARMINE BEE-EATER","CASPIAN TERN","CASSOWARY","CHARA DE COLLAR","CHIPPING SPARROW","CHUKAR PARTRIDGE","CINNAMON TEAL","COCK OF THE  ROCK","COCKATOO","COMMON FIRECREST","COMMON GRACKLE","COMMON HOUSE MARTIN","COMMON LOON","COMMON POORWILL","COMMON STARLING","COUCHS KINGBIRD","CRESTED AUKLET","CRESTED CARACARA","CRESTED NUTHATCH","CROW","CROWNED PIGEON","CUBAN TODY","CURL CRESTED ARACURI","D-ARNAUDS BARBET","DARK EYED JUNCO","DOWNY WOODPECKER","EASTERN BLUEBIRD","EASTERN MEADOWLARK","EASTERN ROSELLA","EASTERN TOWEE","ELEGANT TROGON","ELLIOTS  PHEASANT","EMPEROR PENGUIN","EMU","EURASIAN GOLDEN ORIOLE","EURASIAN MAGPIE","EVENING GROSBEAK","FIRE TAILLED MYZORNIS","FLAME TANAGER","FLAMINGO","FRIGATE","GAMBELS QUAIL","GILA WOODPECKER","GILDED FLICKER","GLOSSY IBIS","GO AWAY BIRD","GOLD WING WARBLER","GOLDEN CHEEKED WARBLER","GOLDEN CHLOROPHONIA","GOLDEN EAGLE","GOLDEN PHEASANT","GOLDEN PIPIT","GOULDIAN FINCH","GRAY CATBIRD","GRAY PARTRIDGE","GREAT POTOO","GREATOR SAGE GROUSE","GREEN JAY","GREY PLOVER","GUINEA TURACO","GUINEAFOWL","GYRFALCON","HARPY EAGLE","HAWAIIAN GOOSE","HELMET VANGA","HOATZIN","HOODED MERGANSER","HOOPOES","HORNBILL","HORNED GUAN","HORNED SUNGEM","HOUSE FINCH","HOUSE SPARROW","IMPERIAL SHAQ","INCA TERN","INDIAN BUSTARD","INDIAN PITTA","INDIGO BUNTING","JABIRU","JAVA SPARROW","JAVAN MAGPIE","KAKAPO","KILLDEAR","KING VULTURE","KIWI","KOOKABURRA","LARK BUNTING","LEARS MACAW","LILAC ROLLER","LONG-EARED OWL","MALABAR HORNBILL","MALACHITE KINGFISHER","MALEO","MALLARD DUCK","MANDRIN DUCK","MARABOU STORK","MASKED BOOBY","MASKED LAPWING","MIKADO  PHEASANT","MOURNING DOVE","MYNA","NICOBAR PIGEON","NORTHERN BALD IBIS","NORTHERN CARDINAL","NORTHERN FLICKER","NORTHERN GANNET","NORTHERN GOSHAWK","NORTHERN JACANA","NORTHERN MOCKINGBIRD","NORTHERN PARULA","NORTHERN RED BISHOP","OCELLATED TURKEY","OKINAWA RAIL","OSPREY","OSTRICH","OYSTER CATCHER","PAINTED BUNTIG","PALILA","PARADISE TANAGER","PARUS MAJOR","PEACOCK","PELICAN","PEREGRINE FALCON","PHILIPPINE EAGLE","PINK ROBIN","PUFFIN","PURPLE FINCH","PURPLE GALLINULE","PURPLE MARTIN","PURPLE SWAMPHEN","QUETZAL","RAINBOW LORIKEET","RAZORBILL","RED BEARDED BEE EATER","RED BELLIED PITTA","RED FACED CORMORANT","RED FACED WARBLER","RED HEADED DUCK","RED HEADED WOODPECKER","RED HONEY CREEPER","RED WINGED BLACKBIRD","RED WISKERED BULBUL","RING-NECKED PHEASANT","ROADRUNNER","ROBIN","ROCK DOVE","ROSY FACED LOVEBIRD","ROUGH LEG BUZZARD","RUBY THROATED HUMMINGBIRD","RUFOUS KINGFISHER","RUFUOS MOTMOT","SAMATRAN THRUSH","SAND MARTIN","SCARLET IBIS","SCARLET MACAW","SHOEBILL","SHORT BILLED DOWITCHER","SMITHS LONGSPUR","SNOWY EGRET","SNOWY OWL","SORA","SPANGLED COTINGA","SPLENDID WREN","SPOON BILED SANDPIPER","SPOONBILL","SRI LANKA BLUE MAGPIE","STEAMER DUCK","STORK BILLED KINGFISHER","STRAWBERRY FINCH","STRIPPED SWALLOW","SUPERB STARLING","SWINHOES PHEASANT","TAIWAN MAGPIE","TAKAHE","TASMANIAN HEN","TEAL DUCK","TIT MOUSE","TOUCHAN","TOWNSENDS WARBLER","TREE SWALLOW","TRUMPTER SWAN","TURKEY VULTURE","TURQUOISE MOTMOT","UMBRELLA BIRD","VARIED THRUSH","VENEZUELIAN TROUPIAL","VERMILION FLYCATHER","VIOLET GREEN SWALLOW","VULTURINE GUINEAFOWL","WATTLED CURASSOW","WHIMBREL","WHITE CHEEKED TURACO","WHITE NECKED RAVEN","WHITE TAILED TROPIC","WILD TURKEY","WILSONS BIRD OF PARADISE","WOOD DUCK","YELLOW BELLIED FLOWERPECKER","YELLOW CACIQUE","YELLOW HEADED BLACKBIRD"
]

def load_image(filename, size=(224,224)):
	# load and resize the image
	pixels = load_img(filename, target_size=size)
	# convert to numpy array
	pixels = img_to_array(pixels)
	# transform in a sample
	pixels = expand_dims(pixels, 0)
	# scale from [0,255] to [-1,1]
	pixels = (pixels - 127.5) / 127.5
	return pixels

def model_type():
    return load_model("h5-model-2.h5")

def image(choice):
    filename = "test/"
    if len(choice) > 1:
        image = load_image(filename + args[1])
    else:
        image = load_image(filename + "3.jpg")
    model = model_type()
    bird = model.predict(image)
    return np.argmax(bird, axis=1)[0], bird.max(axis=1)[0]
     

args = sys.argv 
bird, confidence = image(args)
print("Predicted {} with {}% confidence".format(birds_lst[bird], confidence*100))

